### PR TITLE
Xenial

### PR DESCRIPTION
**Pull request by genevera**

### CODE REVIEW

**Comment by genevera** [comment]
oops! meant to do this on my own fork. sorry!

**Comment by kaaloo** [comment]
Wow this is awesome.  We're actually not using this anymore and I can't test the macos stuff readily.  Looks like you're the farthest along, maybe we can just say your fork is the tip of development?  It looks like @fgrehm is not actively working on this either.  Wdyt?

**Comment by PHPCEO** [comment]
Thanks! And sure, that's fine by me!  

Just need to add in some checks for the apt cacher to get its ip and use it or not, depending.  Maybe a make task to set up and use the container as a system proxy? I have those and use them regularly; just not too sure how to get the Docker VM ip reliably for anything but coreos in xhyve via corectl.

**Comment by genevera** [comment]
Derp.  Github doesn't play nice with multiple accounts in Chrome.

Thanks! And sure, that's fine by me!

Just need to add in some checks for the apt cacher to get its ip and use it or not, depending. Maybe a make task to set up and use the container as a system proxy? I have those and use them regularly; just not too sure how to get the Docker VM ip reliably for anything but coreos in xhyve via corectl.

**Pull request closed without merging**
